# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Lint

on:
  pull_request_target:

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  # Cancel other workflows that are dependent on this workflow by adding jobs that have the same concurrency group.
  cancel_linux:
    name: Cancel running Workflows
    concurrency:
      group: linux-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel Linux"
        run: echo "Cancelling Linux"
  cancel_macos:
    name: Cancel running Workflows
    concurrency:
      group: macos-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel macOS"
        run: echo "Cancelling macOS"
  cancel_coverage:
    name: Cancel running Workflows
    concurrency:
      group: coverage-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel Coverage"
        run: echo "Cancelling Coverage"
  cancel_install:
    name: Cancel running Workflows
    concurrency:
      group: install-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel Install"
        run: echo "Cancelling Install"
  lint:
    name: Lint
    concurrency:
      group: lint-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    needs: [cancel_linux, cancel_macos, cancel_coverage, cancel_install]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Run lint
        uses: seqan/actions/lint@main
        with:
          clang_format: 18
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}
          gpg_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          gpg_passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}

